# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 19:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Request',
            new_name='Wormhole',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='request_id',
            new_name='wormhole_id',
        ),
    ]
