# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 22:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('worms', '0002_auto_20151207_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submitter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='submission',
            name='wormhole_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='worms.Wormhole'),
        ),
        migrations.AlterField(
            model_name='wormhole',
            name='requestor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wormholes', to=settings.AUTH_USER_MODEL),
        ),
    ]
