# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 23:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('worms', '0003_auto_20151207_2226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='submitter_id',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='wormhole',
            name='requestor_id',
        ),
        migrations.AddField(
            model_name='wormhole',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='wormholes', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
