# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worms', '0004_auto_20151207_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='email',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
    ]
