# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worms', '0005_auto_20151208_0334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='location',
        ),
        migrations.AlterField(
            model_name='account',
            name='picture_url',
            field=models.CharField(max_length=1000),
        ),
    ]
