# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 03:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worms', '0006_auto_20151209_0053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='owner',
            new_name='submitter',
        ),
        migrations.RenameField(
            model_name='wormhole',
            old_name='owner',
            new_name='requestor',
        ),
    ]
