# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-10 03:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worms', '0007_auto_20151210_0310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='wormhole_id',
            new_name='wormhole',
        ),
    ]
