# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worms', '0008_auto_20151210_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='fb_id',
            field=models.CharField(default=12345, max_length=200),
            preserve_default=False,
        ),
    ]
