# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-29 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worms', '0010_auto_20151214_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='location',
            field=models.TextField(default=[], max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='submission',
            name='video_thumbnail',
            field=models.TextField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='notes',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='wormhole',
            name='notes',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
