# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 19:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worms', '0011_auto_20151229_0134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='submission',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='wormhole',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='account',
            name='likes',
            field=models.ManyToManyField(related_name='likers', to='worms.Submission'),
        ),
    ]
