# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-02 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worms', '0013_auto_20151231_2025'),
        ('worms', '0012_auto_20151231_2355'),
    ]

    operations = [
    ]
