export const CREATE_REQUEST = 'CREATE_REQUEST';
export const TOGGLE_FETCH = 'TOGGLE_FETCH';
export const UPDATE_INPUT_TEST = 'UPDATE_INPUT_TEST';
export const UPDATE_CURRENT_WORMHOLE = 'UPDATE_CURRENT_WORMHOLE';