export const CREATE_REQUEST = 'CREATE_REQUEST';
export const TOGGLE_FETCH = 'TOGGLE_FETCH';
export const UPDATE_INPUT_TEXT = 'UPDATE_INPUT_TEXT';
export const UPDATE_CURRENT_WORMHOLE = 'UPDATE_CURRENT_WORMHOLE';
export const INIT_CAMERA = 'INIT_CAMERA';
export const SWITCH_CAMERA = 'SWITCH_CAMERA';
export const TOGGLE_CAMERA_RECORDING = 'TOGGLE_CAMERA_RECORDING';
export const TOGGLE_VIDEO_UPLOADING = 'TOGGLE_VIDEO_UPLOADING';
export const UPDATE_WORMHOLE_SUBMISSION_VIDEO = 'UPDATE_WORMHOLE_SUBMISSION_VIDEO ';
export const INIT_PENDING_WORMHOLE_SUBMISSION = 'INIT_PENDING_WORMHOLE_SUBMISSION ';
export const ADD_USER_INFO = 'ADD_USER_INFO';
export const UPDATE_FEED = 'UPDATE_FEED';
export const UPDATE_SUBMISSION_INPUT_TEXT = 'UPDATE_SUBMISSION_INPUT_TEXT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const UPDATE_MY_CURRENT_WORMHOLE = 'UPDATE_MY_CURRENT_WORMHOLE';
export const UPDATE_MY_CURRENT_SUBMISSION = 'UPDATE_MY_CURRENT_SUBMISSION';
export const UPDATE_MY_CURRENT_WORMHOLE_LIST = 'UPDATE_MY_CURRENT_WORMHOLE_LIST';
export const INIT_LIVE_CAMERA = 'INIT_LIVE_CAMERA';
export const UPDATE_LIVE_CAMERA = 'UPDATE_LIVE_CAMERA';

// Initial Login Page
export const CONVERT_FACEBOOK_TOKEN_TO_DJANGO_TOKEN = 'CONVERT_FACEBOOK_TOKEN_TO_DJANGO_TOKEN';

// "Signup" page 
export const UPDATE_SIGNUP_INPUT_TEXT = 'UPDATE_SIGNUP_INPUT_TEXT';
export const UPDATE_SIGNUP_SLIDER = 'UPDATE_SIGNUP_SLIDER';
export const GET_USER_INFO = 'GET_USER_INFO';
export const TOGGLE_ANIMATING = 'TOGGLE_ANIMATING';
export const SET_CLICKED_USER = 'SET_CLICKED_USER';
export const TOGGLE_PEEK_CLICKED_USER = 'TOGGLE_PEEK_CLICKED_USER';
